name = "PlanetaryMagneticFields"
uuid = "548c34cc-0185-415b-8526-a0c739028078"
version = "0.1.0"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["docs", "test"]

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SatelliteToolboxLegendre = "7fa26607-a272-47b2-9aa2-a6c1d419d9d2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
PlanetaryMagneticFieldsMakieExt = "GeoMakie"
PlanetaryMagneticFieldsUnitfulExt = "Unitful"

[compat]
AxisKeys = "0.2"
Bumper = "0.7"
Dates = "1"
GeoMakie = "0.7"
LazyArrays = "2"
LinearAlgebra = "1"
SatelliteToolboxLegendre = "1.1.3"
StaticArrays = "1"
TOML = "1"
Unitful = "1"
julia = "1.10"
